# Custom Language File for Launcher Customizer

[ejs.app]
title = "ULDLauncher"

[ejs.landing]
mediaGitHubURL = "https://github.com/Unleveled-Network/ULDLauncher"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/67KqZqNPRQ"

[ejs.settings]
sourceGithubLink = "https://github.com/Unleveled-Network/ULDLauncher"
supportLink = "https://github.com/Unleveled-Network/ULDLauncher/issues"

[ejs.welcome]
welcomeHeader = "Welcome to Unleveled"
welcomeDescription = "Have a Fun Time"
welcomeDescCTA = "You are just a few clicks away from the action."
